// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biihsfrunulliloaaxju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpaWhzZnJ1bnVsbGlsb2FheGp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NDA1MzEsImV4cCI6MjA3MTMxNjUzMX0.h7psSTWrUrjn6DxLZsVSwVwUD_8yj-QuO1nw35zJyn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});